[31m2025-04-08 19:45:43:4543 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 19:45:47:4547 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 19:46:04:464 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 19:46:47:4647 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 19:48:51:4851 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 19:49:10:4910 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 19:49:19:4919 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 19:49:33:4933 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 19:49:35:4935 error: Error during Data Source initialization connect ECONNREFUSED 127.0.0.1:5432 {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)"}[39m
[31m2025-04-08 20:04:23:423 error: Error during Data Source initialization Entity metadata for Recipe#ingredients was not found. Check if you specified a correct entity object and if it's connected in the connection options. {"stack":"TypeORMError: Entity metadata for Recipe#ingredients was not found. Check if you specified a correct entity object and if it's connected in the connection options.\n    at /usr/apps/api-dev/src/metadata-builder/EntityMetadataBuilder.ts:1121:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.computeInverseProperties (/usr/apps/api-dev/src/metadata-builder/EntityMetadataBuilder.ts:1111:34)\n    at /usr/apps/api-dev/src/metadata-builder/EntityMetadataBuilder.ts:158:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.build (/usr/apps/api-dev/src/metadata-builder/EntityMetadataBuilder.ts:157:25)\n    at ConnectionMetadataBuilder.buildEntityMetadatas (/usr/apps/api-dev/src/connection/ConnectionMetadataBuilder.ts:106:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at DataSource.buildMetadatas (/usr/apps/api-dev/src/data-source/DataSource.ts:712:13)\n    at DataSource.initialize (/usr/apps/api-dev/src/data-source/DataSource.ts:263:13)"}[39m
[31m2025-04-08 20:04:35:435 error: Error during Data Source initialization Entity metadata for Recipe#ingredients was not found. Check if you specified a correct entity object and if it's connected in the connection options. {"stack":"TypeORMError: Entity metadata for Recipe#ingredients was not found. Check if you specified a correct entity object and if it's connected in the connection options.\n    at /usr/apps/api-dev/src/metadata-builder/EntityMetadataBuilder.ts:1121:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.computeInverseProperties (/usr/apps/api-dev/src/metadata-builder/EntityMetadataBuilder.ts:1111:34)\n    at /usr/apps/api-dev/src/metadata-builder/EntityMetadataBuilder.ts:158:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.build (/usr/apps/api-dev/src/metadata-builder/EntityMetadataBuilder.ts:157:25)\n    at ConnectionMetadataBuilder.buildEntityMetadatas (/usr/apps/api-dev/src/connection/ConnectionMetadataBuilder.ts:106:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at DataSource.buildMetadatas (/usr/apps/api-dev/src/data-source/DataSource.ts:712:13)\n    at DataSource.initialize (/usr/apps/api-dev/src/data-source/DataSource.ts:263:13)"}[39m
